### ISSUE TITLE
How to change resolution of Zimage in rhohat.lpp

### ISSUE THREAD

**Issue by agila5** [spatstat/spatstat.linnet#6] opened 2021-08-24 15:45 UTC
Dear developers, I'm not sure if the following reasoning does make sense, but I was wondering if it's possible to modify the code behind `evalCovar.lppm` to adjust the resolution of the object `Zimage` when creating a `linim` object starting from a `linfun` object. In particular, I noticed that, at the moment, the argument `eps` is ignored in `evalCovar.lppm`, and I was wondering if it can be used when creating the `linim` object named `Zimage`. 

I tried to implement that idea in a separate [fork](https://github.com/agila5/spatstat.linnet/commit/1d3768a3c53c7ba0c0b0507fb619f2e6d6b50a2e) of this repository and this is the result: 

``` r
library(spatstat.linnet)
set.seed(1)
Y <- runiflpp(50, domain(chicago))
rhoY <- rhohat(Y, "y", eps = 5)
plot(predict(rhoY))
```

![](https://i.imgur.com/KgaPT8b.png)

``` r
rhoY <- rhohat(Y, "y", eps = 20)
plot(predict(rhoY))
```

![](https://i.imgur.com/Gs8SclX.png)

<sup>Created on 2021-08-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

(the current version returns a 128 x 128 image in both cases). 

I'm not sure the resolution of `Zimage` can be modified like that, and I'm not sure I can "reuse" the argument `eps` (since it defines the grid used to evaluate the covariate). In any case, if you agree, I could complete the implementation and create a pull request. 

Sorry for all these issues.

**Comment by baddstats** [comment] 2021-08-25 06:59
The implementation of `evalCovar.lppm` is not yet finished, so the argument `eps` is not currently handled by the code. 

However, the argument `eps` was intended to control the spacing of sample points along the network, not the pixel size of the approximating pixel image. The usage of `eps` and `nd` was meant to be similar to their use in `lppm`. 

(I assume you are aware that a `linim` object carries two sets of data, one of which is a pixel image of class `im`, and the other is a data frame representing sample points along the network.)

But I can see that it would be useful to control the resolution of the approximating pixel image as well as the sample point data. 

I will change the specification, so that `evalCovar.lppm` accepts arguments `eps` and `dimyx` (which will be interpreted by `as.mask` to control pixel dimensions of the image) and `delta` and `nd` (to control the spacing of sample points along the network).

Finally, you didn't say why you needed to change the pixel resolution, but if it was purely to improve the graphics, then it would be easier to use the argument `fatten` in  `plot.linim`.

**Comment by agila5** [comment] 2021-08-25 07:31
Thank you very much for your answer. 

> I will change the specification, so that evalCovar.lppm accepts arguments eps and dimyx (which will be interpreted by as.mask to control pixel dimensions of the image) and delta and nd (to control the spacing of sample points along the network).

Ok, thanks. 

> Finally, you didn't say why you needed to change the pixel resolution, but if it was purely to improve the graphics, then it would be easier to use the argument fatten in plot.linim.

Yes, it is just for graphical purposes since the output image does not look great for larger linear networks. Unfortunately, I forgot about fatten argument in plot.linim so, for the moment, I will just change that parameter.

**Comment by baddstats** [comment] 2021-08-25 08:40
Done (in `spatstat.linnet 2.3-0.002`)

**Closed as completed by baddstats** 2021-08-25 08:40 UTC
